name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: cd message_live && npm install

      - name: Build the project
        run: cd message_live && npm run build
        env:
          MONGO: ${{ secrets.MONGO }}
          API: ${{ secrets.API }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: message_live/dist  # Chemin vers le répertoire de build de votre projet
          publish_branch: gh-pages  # Branche cible pour GitHub Pages
